### PR TITLE
add dll name into sys: pragma

### PR DESCRIPTION
**Pull request by mattn**
related on https://github.com/cznic/99c/issues/2

add dll name for sys pragma.

98cbc40744e472b3

For testing MessageBox, you need to add MessageBoxA/MessageBoxW into windows.go and `go generate` (also put them into cpu.go, enum.go)

### CODE REVIEW

**Review by cznic — APPROVED** [review]
LGTM but please make sure that `go test github.com/cznic/ccir` passes before merging. I don't have a Windows box and cannot test it. Thank you.

**Comment by mattn** [comment]
currently, ccir doesn't pass tests on Windows.
```
--- FAIL: TestGCCExec (10.97s)
	all_test.go:359: ..\cc\testdata\gcc-6.3.0\gcc\testsuite\gcc.c-torture\execute\loop-2f.c: FAIL
		cc.Parse: ..\cc\testdata\gcc-6.3.0\gcc\testsuite\gcc.c-torture\execute\loop-2f.c:44:33: expected 'int' but argument is of type '<undefined>'
		..\cc\testdata\gcc-6.3.0\gcc\testsuite\gcc.c-torture\execute\loop-2f.c:48:33: undefined: PROT_READ
		..\cc\testdata\gcc-6.3.0\gcc\testsuite\gcc.c-torture\execute\loop-2f.c:49:25: undefined: MAP_PRIVATE
		c:\dev\go\src\github.com\cznic\ccir\libc\sys\mman.h:8:19: include file not found: sys/mman_windows_amd64.h
		c:\dev\go\src\github.com\cznic\ccir\libc\sys\types.h:10:19: include file not found: sys/types_windows_amd64.h
	all_test.go:368: 1249/1251 ok
	all_test.go:370: failures: 2
FAIL
exit status 1
FAIL	github.com/cznic/ccir	12.235s
```

**Comment by cznic** [comment]
Can you please try if the tests pass on the master branch?

**Comment by mattn** [comment]
It is same. PROT_READ/MAP_PRIVATE is not defined on Windows. Also O_RDONLY is not defined in default. So test should be fail.

**Comment by cznic** [comment]
> It is same. PROT_READ/MAP_PRIVATE is not defined on Windows. Also O_RDONLY is not defined in default. So test should be fail.

OK then, go ahead and merge to master branch, thank you,

**Pull request merged**
